apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-application-svc
  name: web-application-svc
spec:
  type: NodePort
  selector:
    app: web-application
  ports:
  - name: targetport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007